"""Generate/check the backend-only upload-text handoff schema from its public models."""

import argparse
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT.parents[1] / "backend"))

from pydantic.json_schema import models_json_schema  # noqa: E402
from services.api.text_schemas import DeviceTextRead, TextBatch, TextCompletion  # noqa: E402

SCHEMA = ROOT / "schemas" / "device-text.schema.json"


def schema() -> dict[str, Any]:
    _, document = models_json_schema(
        [(TextBatch, "validation"), (TextCompletion, "validation"), (DeviceTextRead, "validation")]
    )

    def normalize(node: Any) -> None:
        if isinstance(node, dict):
            if node.pop("format", None) == "uuid":
                node["pattern"] = "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
            if "anyOf" in node:
                node["oneOf"] = node.pop("anyOf")
            if "properties" in node:
                node["additionalProperties"] = False
            for value in node.values():
                normalize(value)
        elif isinstance(node, list):
            for value in node:
                normalize(value)

    normalize(document)
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$comment": "Ovrly contracts 0.2.0-draft. Generated by device_text.py; backend-only v1.",
        "title": "Completed-upload device text",
        "description": (
            "Synthetic-tested backend handoff, not the Android live-capture chunk wire format. "
            "Completion records delivery, not continuous coverage or successful OCR. "
            "Cross-field identity, timestamp, region-outcome and source-budget checks are "
            "also enforced by the server; see README."
        ),
        **document,
        "oneOf": [
            {"$ref": "#/$defs/TextBatch"},
            {"$ref": "#/$defs/TextCompletion"},
            {"$ref": "#/$defs/DeviceTextRead"},
        ],
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--update", action="store_true")
    args = parser.parse_args()
    expected = json.dumps(schema(), indent=2, ensure_ascii=False) + "\n"
    if args.update:
        SCHEMA.write_text(expected, encoding="utf-8")
    elif not SCHEMA.exists() or SCHEMA.read_text(encoding="utf-8") != expected:
        print("Device-text schema drift: run device_text.py --update", file=sys.stderr)
        return 1
    print("Upload-text schema matches the backend models.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
